@extends('layouts.app')
@section('title', 'Employee Board')

@section('content')
<div x-data="{
    search: '{{ request('search', '') }}',
    showAddModal: false,
    payrollMode: '{{ request('payroll_mode', '') }}',
    departmentId: '{{ request('department_id', '') }}',

    // New Employee Form State
    newEmployeeCode: '',
    newPayrollMode: 'monthly_staff',
    newDepartmentId: '',
    codeLoading: false,
    codeAutoGenerated: true,

    async generateCode() {
        if (!this.codeAutoGenerated) return;
        this.codeLoading = true;
        try {
            const params = new URLSearchParams();
            if (this.newDepartmentId) params.set('department_id', this.newDepartmentId);
            if (this.newPayrollMode) params.set('payroll_mode', this.newPayrollMode);
            const resp = await fetch('{{ route('employees.generate-code') }}?' + params.toString());
            const data = await resp.json();
            if (data.code && this.codeAutoGenerated) {
                this.newEmployeeCode = data.code;
            }
        } catch (e) {
            console.error('Failed to generate code:', e);
        } finally {
            this.codeLoading = false;
        }
    }
}">
    @php
        $viewMode = request('view') === 'table' ? 'table' : 'card';
        $cardViewUrl = route('employees.index', array_merge(request()->query(), ['view' => 'card']));
        $tableViewUrl = route('employees.index', array_merge(request()->query(), ['view' => 'table']));
    @endphp

    <!-- Header -->
    <div class="flex items-center justify-between mb-6">
        <h1 class="text-2xl font-bold text-gray-900">Employee Board</h1>
        <div class="flex items-center gap-2">
            <div class="inline-flex rounded-lg border border-gray-300 bg-white p-1">
                <a href="{{ $cardViewUrl }}"
                    class="px-3 py-1.5 rounded-md text-xs font-semibold transition {{ $viewMode === 'card' ? 'bg-indigo-600 text-white' : 'text-gray-600 hover:bg-gray-100' }}">
                    การ์ด
                </a>
                <a href="{{ $tableViewUrl }}"
                    class="px-3 py-1.5 rounded-md text-xs font-semibold transition {{ $viewMode === 'table' ? 'bg-indigo-600 text-white' : 'text-gray-600 hover:bg-gray-100' }}">
                    ตาราง
                </a>
            </div>
            <button @click="showAddModal = true; if(!newEmployeeCode) generateCode()" class="bg-indigo-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-indigo-700 transition">
                + เพิ่มพนักงาน
            </button>
        </div>
    </div>

    <!-- Filters -->
    <form method="GET" action="{{ route('employees.index') }}" class="flex flex-wrap items-center gap-3 mb-6">
        <input type="hidden" name="view" value="{{ $viewMode }}">
        <input type="text" name="search" x-model="search" placeholder="ค้นหาชื่อ / รหัส..."
            class="px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-indigo-500 focus:border-indigo-500 w-64">
        <select name="payroll_mode" x-model="payrollMode" class="px-3 py-2 border border-gray-300 rounded-lg text-sm">
            <option value="">ทุก Payroll Mode</option>
            <option value="monthly_staff">พนักงานรายเดือน</option>
            <option value="office_staff">พนักงานออฟฟิศ</option>
            <option value="freelance_layer">ฟรีแลนซ์</option>
            <option value="youtuber_salary">YouTuber เงินเดือน</option>
            <option value="youtuber_settlement">YouTuber Settlement</option>
        </select>
        <select name="department_id" x-model="departmentId" class="px-3 py-2 border border-gray-300 rounded-lg text-sm">
            <option value="">ทุกแผนก</option>
            @foreach($departments as $dept)
            <option value="{{ $dept->id }}">{{ $dept->name }}</option>
            @endforeach
        </select>
        
        <div class="h-8 w-px bg-gray-300 mx-1"></div>

        <div class="flex items-center gap-2">
            <span class="text-xs font-semibold text-gray-500 uppercase">จัดกลุ่ม:</span>
            <select name="group_by" class="px-3 py-2 border border-gray-300 rounded-lg text-sm bg-indigo-50 border-indigo-200 text-indigo-700" onchange="this.form.submit()">
                <option value="none" {{ $groupBy === 'none' ? 'selected' : '' }}>ไม่มี</option>
                <option value="department" {{ $groupBy === 'department' ? 'selected' : '' }}>แผนก</option>
                <option value="payroll_mode" {{ $groupBy === 'payroll_mode' ? 'selected' : '' }}>Payroll Mode</option>
            </select>
        </div>

        <label class="flex items-center gap-2 text-sm text-gray-600 cursor-pointer">
            <input type="checkbox" name="show_inactive" value="1" {{ $showInactive ? 'checked' : '' }} class="rounded border-gray-300 text-indigo-600" onchange="this.form.submit()">
            แสดงพนักงานที่ระงับ
        </label>
        <button type="submit" class="bg-gray-100 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-200 ml-auto">ค้นหา</button>
    </form>

    @php
        $modeMeta = [
            'monthly_staff' => ['label' => 'พนักงานรายเดือน', 'badge' => 'bg-blue-100 text-blue-700'],
            'office_staff' => ['label' => 'พนักงานออฟฟิศ', 'badge' => 'bg-cyan-100 text-cyan-700'],
            'freelance_layer' => ['label' => 'ฟรีแลนซ์', 'badge' => 'bg-green-100 text-green-700'],
            'youtuber_salary' => ['label' => 'YouTuber เงินเดือน', 'badge' => 'bg-purple-100 text-purple-700'],
            'youtuber_settlement' => ['label' => 'YouTuber Settlement', 'badge' => 'bg-orange-100 text-orange-700'],
            'custom_hybrid' => ['label' => 'รูปแบบผสม', 'badge' => 'bg-pink-100 text-pink-700'],
        ];

        $modeOrder = array_keys($modeMeta);
        $groupedEmployees = $employees->groupBy('payroll_mode')->sortBy(function ($_, $mode) use ($modeOrder) {
            $position = array_search($mode, $modeOrder, true);
            return $position === false ? 999 : $position;
        });
    @endphp

    @if($viewMode === 'table')
    <div class="mb-8 bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
        <div class="overflow-x-auto">
            <table class="min-w-full text-sm">
                <thead class="bg-gray-50 border-b border-gray-200">
                    <tr class="text-left text-gray-600">
                        @php
                            $sortLink = function($field, $label) use ($sortBy, $sortDir) {
                                $isCurrent = $sortBy === $field;
                                $newDir = ($isCurrent && $sortDir === 'asc') ? 'desc' : 'asc';
                                $icon = '';
                                if ($isCurrent) {
                                    $icon = $sortDir === 'asc' 
                                        ? '<svg class="w-3 h-3 ml-1 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 15l7-7 7 7"></path></svg>'
                                        : '<svg class="w-3 h-3 ml-1 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M19 9l-7 7-7-7"></path></svg>';
                                }
                                $url = route('employees.index', array_merge(request()->query(), ['sort_by' => $field, 'sort_dir' => $newDir]));
                                return '<a href="'.$url.'" class="hover:text-indigo-600 flex items-center">'.$label.$icon.'</a>';
                            };
                        @endphp
                        <th class="px-4 py-3 font-semibold">{!! $sortLink('first_name', 'ชื่อ') !!}</th>
                        <th class="px-4 py-3 font-semibold">{!! $sortLink('employee_code', 'รหัส') !!}</th>
                        <th class="px-4 py-3 font-semibold text-center">{!! $sortLink('payroll_mode', 'Payroll Mode') !!}</th>
                        <th class="px-4 py-3 font-semibold">{!! $sortLink('department', 'แผนก') !!}</th>
                        <th class="px-4 py-3 font-semibold">ตำแหน่ง</th>
                        <th class="px-4 py-3 font-semibold text-right">{!! $sortLink('salary', 'เงินเดือนฐาน') !!}</th>
                        <th class="px-4 py-3 font-semibold text-center">สถานะ</th>
                        <th class="px-4 py-3 font-semibold text-right">จัดการ</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-100">
                    @php
                        if ($groupBy === 'department') {
                            $employeesGrouped = $employees->groupBy(fn($emp) => $emp->department?->name ?? 'ไม่ระบุแผนก');
                        } elseif ($groupBy === 'payroll_mode') {
                            $employeesGrouped = $employees->groupBy(fn($emp) => $modeMeta[$emp->payroll_mode]['label'] ?? $emp->payroll_mode);
                        } else {
                            $employeesGrouped = ['ทั้งหมด' => $employees];
                        }
                    @endphp

                    @forelse($employeesGrouped as $groupName => $groupContent)
                        @if($groupBy !== 'none')
                        <tr class="bg-gray-100/50">
                            <td colspan="8" class="px-4 py-2 font-bold text-gray-700 border-l-4 border-indigo-500">
                                {{ $groupName }} 
                                <span class="ml-2 px-2 py-0.5 rounded-full bg-white border text-[10px] text-gray-500">{{ $groupContent->count() }} คน</span>
                            </td>
                        </tr>
                        @endif

                        @foreach($groupContent as $emp)
                        <tr class="{{ !$emp->is_active ? 'bg-gray-50 text-gray-500' : '' }} hover:bg-slate-50 transition">
                            <td class="px-4 py-3 font-medium">{{ $emp->display_name }}</td>
                            <td class="px-4 py-3 font-mono text-xs text-gray-500">{{ $emp->employee_code ?: 'NO-CODE' }}</td>
                            <td class="px-4 py-3 text-center">
                                <span class="inline-block px-2 py-0.5 rounded-full text-xs font-medium {{ $modeMeta[$emp->payroll_mode]['badge'] ?? 'bg-gray-100 text-gray-700' }}">
                                    {{ $modeMeta[$emp->payroll_mode]['label'] ?? $emp->payroll_mode }}
                                </span>
                            </td>
                            <td class="px-4 py-3">{{ $emp->department?->name ?? '-' }}</td>
                            <td class="px-4 py-3">{{ $emp->position?->name ?? '-' }}</td>
                            <td class="px-4 py-3 text-right font-mono">{{ $emp->salaryProfile ? number_format($emp->salaryProfile->base_salary, 0) . ' ฿' : '-' }}</td>
                            <td class="px-4 py-3 text-center">
                                <span class="inline-flex items-center px-2 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider {{ $emp->is_active ? 'bg-green-100 text-green-700' : 'bg-gray-200 text-gray-600' }}">
                                    {{ $emp->is_active ? 'ใช้งาน' : 'ระงับ' }}
                                </span>
                            </td>
                            <td class="px-4 py-3">
                                <div class="flex items-center justify-end gap-2">
                                    <a href="{{ route('workspace.show', ['employee' => $emp->id, 'month' => now()->month, 'year' => now()->year]) }}"
                                       class="px-2.5 py-1.5 rounded-md bg-indigo-50 text-indigo-700 text-xs font-semibold hover:bg-indigo-600 hover:text-white transition">
                                        Workspace
                                    </a>
                                    <a href="{{ route('employees.edit', $emp->id) }}"
                                       class="px-2.5 py-1.5 rounded-md bg-white border border-gray-300 text-gray-700 text-xs font-semibold hover:bg-gray-50">
                                        Edit
                                    </a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    @empty
                    <tr>
                        <td colspan="8" class="px-4 py-8 text-center text-gray-500 italic">ไม่พบพนักงานตามเงื่อนไขที่ค้นหา</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
    @endif

    @if($viewMode === 'card')
    <div>
    @forelse($groupedEmployees as $mode => $employeesInMode)
    <section class="mb-8">
        <div class="flex items-center justify-between mb-3">
            <h2 class="text-lg font-semibold text-gray-900">{{ $modeMeta[$mode]['label'] ?? $mode }}</h2>
            <span class="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-700">
                {{ $employeesInMode->count() }} คน
            </span>
        </div>

        <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
            @foreach($employeesInMode as $emp)
            <div class="relative group">
                <a href="{{ route('workspace.show', ['employee' => $emp->id, 'month' => now()->month, 'year' => now()->year]) }}"
                class="block h-full bg-white rounded-xl shadow-sm border border-gray-200 p-4 hover:shadow-md hover:border-indigo-300 transition {{ !$emp->is_active ? 'grayscale opacity-60 bg-gray-50' : '' }}">
                    <div class="flex items-center justify-center w-12 h-12 rounded-full {{ $emp->is_active ? 'bg-indigo-100 text-indigo-600' : 'bg-gray-200 text-gray-500' }} font-bold text-lg mb-3 mx-auto">
                        {{ mb_substr($emp->display_name, 0, 1) }}
                    </div>
                    <h3 class="text-center font-semibold {{ $emp->is_active ? 'text-gray-900' : 'text-gray-500' }} text-sm truncate">{{ $emp->display_name }}</h3>
                    <p class="text-center text-[11px] text-gray-400 mt-1 font-mono">{{ $emp->employee_code ?: 'NO-CODE' }}</p>
                    <p class="text-center text-xs text-gray-500 mt-1">{{ $emp->position?->name ?? '-' }}</p>
                    <div class="mt-2 text-center">
                        <span class="inline-block px-2 py-0.5 rounded-full text-xs font-medium {{ $modeMeta[$emp->payroll_mode]['badge'] ?? 'bg-gray-100 text-gray-700' }}">
                            {{ $modeMeta[$emp->payroll_mode]['label'] ?? $emp->payroll_mode }}
                        </span>
                    </div>

                    @if(in_array($emp->payroll_mode, ['freelance_layer', 'youtuber_salary']))
                    <div class="mt-2 text-center">
                        @php $avgMin = $emp->average_minutes_last_3_months; @endphp
                        <span class="inline-block px-2 py-0.5 rounded-full text-[10px] font-bold 
                            {{ $avgMin < 100 ? 'bg-red-100 text-red-700 border border-red-200' : 'bg-gray-100 text-gray-600' }}">
                            Avg: {{ number_format($avgMin, 1) }}m
                            @if($avgMin < 100) ⚠️ @endif
                        </span>
                    </div>
                    @endif

                    @if($emp->salaryProfile && $emp->salaryProfile->base_salary > 0)
                    <p class="text-center text-sm font-semibold text-gray-700 mt-2">
                        {{ number_format($emp->salaryProfile->base_salary, 0) }} ฿
                    </p>
                    @endif
                </a>

                <a href="{{ route('employees.edit', $emp->id) }}"
                   class="absolute top-2 left-2 opacity-0 group-hover:opacity-100 transition-opacity px-2 py-1 rounded-md bg-white shadow-sm border border-gray-200 text-[11px] font-medium text-indigo-600 hover:bg-indigo-50"
                   title="แก้ไขข้อมูลพนักงาน"
                   onclick="event.stopPropagation()">
                    EDIT
                </a>

                <!-- Toggle Status Button -->
                <form action="{{ route('employees.toggle-status', $emp->id) }}" method="POST" class="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    @csrf
                    @method('PATCH')
                    <button type="submit" class="p-1 rounded-full bg-white shadow-sm border border-gray-200 hover:bg-gray-50 {{ $emp->is_active ? 'text-red-500' : 'text-green-500' }}" title="{{ $emp->is_active ? 'ระงับพนักงาน' : 'เปิดใช้งานพนักงาน' }}">
                        @if($emp->is_active)
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728L5.636 5.636" />
                        </svg>
                        @else
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        @endif
                    </button>
                </form>
            </div>
            @endforeach

            @if($loop->first)
            <!-- Add Card -->
            <button @click="showAddModal = true"
                class="bg-white rounded-xl shadow-sm border-2 border-dashed border-gray-300 p-4 flex flex-col items-center justify-center min-h-[160px] hover:border-indigo-400 hover:bg-indigo-50 transition cursor-pointer">
                <div class="w-12 h-12 rounded-full bg-gray-100 flex items-center justify-center text-gray-400 text-2xl mb-2">+</div>
                <span class="text-sm text-gray-500">เพิ่มพนักงาน</span>
            </button>
            @endif
        </div>
    </section>
    @empty
    <div class="bg-white rounded-xl border border-dashed border-gray-300 p-8 text-center text-gray-500">
        ไม่พบพนักงานตามเงื่อนไขที่ค้นหา
    </div>
    @endforelse
    </div>
    @endif

    <!-- Add Employee Modal -->
    <div x-show="showAddModal" x-cloak class="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" @click.self="showAddModal = false">
        <div class="bg-white rounded-2xl shadow-xl w-full max-w-lg max-h-[90vh] overflow-y-auto" @click.stop>
            <form method="POST" action="{{ route('employees.store') }}" class="p-6">
                @csrf
                <h2 class="text-lg font-bold mb-4">เพิ่มพนักงานใหม่</h2>

                <div class="grid grid-cols-2 gap-4">
                    <div>
                        <label class="block text-xs font-medium text-gray-600 mb-1">ชื่อ *</label>
                        <input type="text" name="first_name" required class="w-full px-3 py-2 border rounded-lg text-sm">
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-gray-600 mb-1">นามสกุล *</label>
                        <input type="text" name="last_name" required class="w-full px-3 py-2 border rounded-lg text-sm">
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-gray-600 mb-1">ชื่อเล่น</label>
                        <input type="text" name="nickname" class="w-full px-3 py-2 border rounded-lg text-sm">
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-gray-600 mb-1">รหัสพนักงาน</label>
                        <div class="flex items-center gap-1">
                            <input type="text" name="employee_code" x-model="newEmployeeCode"
                                   @input="codeAutoGenerated = false"
                                   class="w-full px-3 py-2 border rounded-lg text-sm"
                                   :class="codeLoading ? 'bg-gray-50 text-gray-400' : ''">
                            <button type="button" @click="codeAutoGenerated = true; generateCode()"
                                    class="p-2 bg-gray-100 border border-gray-300 rounded-lg text-gray-500 hover:bg-gray-200" title="สร้างรหัสใหม่">
                                <svg class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
                            </button>
                        </div>
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-gray-600 mb-1">Payroll Mode *</label>
                        <select name="payroll_mode" x-model="newPayrollMode" @change="generateCode()" required class="w-full px-3 py-2 border rounded-lg text-sm">
                            <option value="monthly_staff">พนักงานรายเดือน</option>
                            <option value="office_staff">พนักงานออฟฟิศ</option>
                            <option value="freelance_layer">ฟรีแลนซ์</option>
                            <option value="youtuber_salary">YouTuber เงินเดือน</option>
                            <option value="youtuber_settlement">YouTuber Settlement</option>
                        </select>
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-gray-600 mb-1">แผนก</label>
                        <select name="department_id" x-model="newDepartmentId" @change="generateCode()" class="w-full px-3 py-2 border rounded-lg text-sm">
                            <option value="">-</option>
                            @foreach($departments as $dept)
                            <option value="{{ $dept->id }}">{{ $dept->name }} ({{ $dept->code }})</option>
                            @endforeach
                        </select>
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-gray-600 mb-1">ตำแหน่ง</label>
                        <select name="position_id" class="w-full px-3 py-2 border rounded-lg text-sm">
                            <option value="">-</option>
                            @foreach($positions as $pos)
                            <template x-if="newDepartmentId == '' || newDepartmentId == '{{ $pos->department_id }}'">
                                <option value="{{ $pos->id }}">{{ $pos->name }} ({{ $pos->department?->code }})</option>
                            </template>
                            @endforeach
                        </select>
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-gray-600 mb-1">เงินเดือน</label>
                        <input type="number" name="base_salary" step="0.01" class="w-full px-3 py-2 border rounded-lg text-sm">
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-gray-600 mb-1">วันเริ่มงาน</label>
                        <input type="date" name="start_date" class="w-full px-3 py-2 border rounded-lg text-sm">
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-gray-600 mb-1">ธนาคาร</label>
                        <input type="text" name="bank_name" class="w-full px-3 py-2 border rounded-lg text-sm">
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-gray-600 mb-1">เลขบัญชี</label>
                        <input type="text" name="account_number" class="w-full px-3 py-2 border rounded-lg text-sm">
                    </div>
                </div>

                <div class="flex justify-end gap-3 mt-6">
                    <button type="button" @click="showAddModal = false" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">ยกเลิก</button>
                    <button type="submit" class="px-4 py-2 text-sm bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">บันทึก</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
